apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yetcwkb20-go
  janus-idp.io/tekton: yetcwkb20-go
  backstage.io/kubernetes-id: yetcwkb20-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yetcwkb20-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
