apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yetcwkb20-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yetcwkb20-go 
  name: yetcwkb20-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yetcwkb20-go 
